### ISSUE TITLE
Open github link on new window

### ISSUE THREAD

**Issue by Sandstedt** [mojs/mojs-player#1]
Would be great if the link [https://github.com/legomushroom/mojs-player](https://github.com/legomushroom/mojs-player) in the bottom right of the player opens in a new tab (`target="_blank"`).

Error on CodePen when clicking on the mojs logo:
`Refused to display 'https://github.com/legomushroom/mojs-player' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

**Comment by legomushroom** [comment]
@Sandstedt hm, seems like codepen error. Not sure about `target="_blank"` - from one side it will ensure that user won't loose the context of the current page. From other side - some users can be frustrated since we are deciding for them how to proceed to the next page (they just can hold `super` key when clicking). What do you think?

**Comment by Sandstedt** [comment]
It has to do with github's server header restrictions (I think). They will not allow loading their site in an iframe. Such small thing, so I think it's better to make it work on CodePen, because all of the examples on the site uses CodePen.

Usually avoid opening in a new window, but in this case I thinks it's the best.

**Comment by legomushroom** [comment]
makes sense. mind to submit a PR?

**Comment by legomushroom** [comment]
Pushed the fix, thanks for the issue!
